feat: fragment to extension migration
hamlet-io/engine-plugin-aws pull request #194
Opened 2020-12-09 22:59 UTC by roleyfoley

## Description
aws implementation of https://github.com/hamlet-io/engine/pull/1494 
Updates all components which currently support fragments to the new
extensions process which includes support for fragments. 

## Motivation and Context

This allows for
extensions to be defined as part of our plugin setup and allows for
components to call multiple extensions

## How Has This Been Tested?
Tested locally and with test suite

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions
- [ ] Requires: https://github.com/hamlet-io/engine/pull/1494

## Checklist:
- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] None of the above.

2020-12-15 01:26 UTC, ml019 requested changes

2020-12-15 01:26 UTC, ml019 commented on aws/components/apigateway/setup.ftl
> +    [#if solution.Extensions?has_content ]
For consistency with other components, suggest we drop the if test.

2020-12-15 01:26 UTC, ml019 commented on aws/components/user/setup.ftl
> +    [#if solution.Extensions?has_content ]
Remove if for consistency

2020-12-17 00:32 UTC, RossMurr4y approved these changes
Approved, leaving to @ml019 to review as per his previous comments

2020-12-17 10:43 UTC, merged