feat: add ec2 image source support for aws
hamlet-io/engine-plugin-aws pull request #269
Opened 2021-04-10 05:52 UTC by roleyfoley

## Intent of Change

- New feature (non-breaking change which adds functionality)

## Description

Adds support for configuring the AMI image of ec2 based components using
the image source configuration options.

Adds two AWS specific image source attributes to handle more explicit configuration options
- Source:AMI - Allows a user to explicitly define an AMI Id to use at the component level
- Source:SSMParam - Allows the user to define an SSM Parameter that holds the Image Id. The default value for these options is the AWS public parameters which list the latest recommended version of AWS provided AMI Images.

The default behaviour is to use the current AMI Ids defined in the
Region objects

Also includes a minor update to the ec2 component which enables CFN signal for the init process and requires CFN signal to complete on creation of the resource 

## Motivation and Context

This allows for users to have greater control over the AMI that is used for the virtual machine based components. Using the Public SSM parameters allows for deployments to automatically use the latest version of the image available from AWS at the time of deployment without having to depend on updates to hamlet to use the reference configuration 

## How Has This Been Tested?

Tested locally 

## Followup Actions

- [x] None

2021-04-12 00:22 UTC, RossMurr4y submitted a review, later dismissed

2021-04-12 02:55 UTC, roleyfoley commented
More to come moving back to draft

2021-04-15 00:16 UTC, ml019 commented
@roleyfoley #271 now merged - pls rebase and I'll review again

2021-04-15 01:28 UTC, roleyfoley commented
@ml019 Rebased, fixed and should be good to go now

2021-04-15 01:37 UTC, ml019 requested changes

2021-04-15 01:37 UTC, ml019 commented on aws/attributesets/attributeset.ftl
> +[#assign AWS_ECS_COMPUTEIMAGE_ATTRIBUTESET_TYPE = "aws_ecs_comptueimage"]
```suggestion
[#assign AWS_ECS_COMPUTEIMAGE_ATTRIBUTESET_TYPE = "aws_ecs_computeimage"]
```

2021-04-15 02:44 UTC, ml019 approved these changes

2021-04-15 02:44 UTC, merged