feat(backup): Initial AWS implementation
hamlet-io/engine-plugin-aws pull request #507
Opened 2022-01-26 10:33 UTC by ml019

## Intent of Change
- New feature (non-breaking change which adds functionality)

## Description
Adds support for backup stores based on AWS Backup.

A backupstore is implemented as a backup vault, while each backupregime receives a backup plan and selection.

Also included is the RDS support for tagging. If the RDS component is linked to a backup regime, the cluster is also tagged with the specific tag for the regime.

## Motivation and Context
Part of https://github.com/hamlet-io/engine/issues/1917

## How Has This Been Tested?
- Local template generation
- Further customer testing will be undertaken once the component has been released

## Related Changes

### Prerequisite PRs:
- engine - https://github.com/hamlet-io/engine/pull/1921

### Dependent PRs:

- None

### Consumer Actions:

- None

2022-01-26 10:34 UTC, ml019 commented
@roleyfoley I've added a test module for AWS but it fails to be listed as an available deployment. Not sure what I've missed - does the test module has to explicitly by configured somewhere?

2022-01-27 00:45 UTC, roleyfoley approved these changes

2022-01-27 00:45 UTC, roleyfoley commented
> @roleyfoley I've added a test module for AWS but it fails to be listed as an available deployment. Not sure what I've missed - does the test module has to explicitly by configured somewhere?

Yes it needs to be included in the inputseeder which that loads the modules into the blueprint

2022-01-27 00:46 UTC, roleyfoley requested changes
Testing currently not working

2022-01-27 05:55 UTC, roleyfoley approved these changes

2022-01-27 05:55 UTC, merged